import type { Metadata } from "next";
import { Lato } from "next/font/google"; 
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: '--font-lato' 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.className}>
      <body className="antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  );
}